const log1Contributions = [
  {
    ContributionID: 3,
    ContributionLogID: 1,
    ContributionUserID: 289,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Research 'problems we may run into' i.e. cost, waste and time",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 1",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "ALAHMAD, Samir (K7907243)",
  },
  {
    ContributionID: 4,
    ContributionLogID: 1,
    ContributionUserID: 474,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Research 'how to educate' the public better on nuclear energy",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 1",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "PAULINO DA SILVA, Marius (K2831579)",
  },
  {
    ContributionID: 5,
    ContributionLogID: 1,
    ContributionUserID: 343,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Research 'the problem' combatting the decrease in natural resources ",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 1",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "DARCY, Alexander (K9989999)",
  },
  {
    ContributionID: 6,
    ContributionLogID: 1,
    ContributionUserID: 464,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Research 'the why' the public fear with nuclear power",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 1",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "OBOUSY, Usama (K7463732)",
  },
  {
    ContributionID: 7,
    ContributionLogID: 1,
    ContributionUserID: 325,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Research 'benefits to the economy' for nuclear energy over natural resources",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 1",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "BHAMRA, Shakiba (K9804915)",
  },
];
export default log1Contributions;
