const log4Contributions = [
  {
    ContributionID: 18,
    ContributionLogID: 4,
    ContributionUserID: 289,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Work on a script for your slides section and time yourself giving the talk, to fit within the template ",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 4",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "ALAHMAD, Samir (K7907243)",
  },
  {
    ContributionID: 19,
    ContributionLogID: 4,
    ContributionUserID: 474,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Work on a script for your slides section and time yourself giving the talk, to fit within the template",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 4",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "PAULINO DA SILVA, Marius (K2831579)",
  },
  {
    ContributionID: 20,
    ContributionLogID: 4,
    ContributionUserID: 343,
    ContributionAttendanceID: 2,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Work on a script for your slides section and time yourself giving the talk, to fit within the template",
    ContributionAttendanceName: "Late arriving",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 4",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "DARCY, Alexander (K9989999)",
  },
  {
    ContributionID: 21,
    ContributionLogID: 4,
    ContributionUserID: 464,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Work on a script for your slides section and time yourself giving the talk, to fit within the template",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 4",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "OBOUSY, Usama (K7463732)",
  },
  {
    ContributionID: 22,
    ContributionLogID: 4,
    ContributionUserID: 325,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Work on a script for your slides section and time yourself giving the talk, to fit within the template",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 4",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "BHAMRA, Shakiba (K9804915)",
  },
];
export default log4Contributions;

