const log3Contributions = [
  {
    ContributionID: 13,
    ContributionLogID: 3,
    ContributionUserID: 289,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Add to the Powerpoint Presentation including extended ideas for your chosen section: Value Proposition",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 3",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "ALAHMAD, Samir (K7907243)",
  },
  {
    ContributionID: 15,
    ContributionLogID: 3,
    ContributionUserID: 343,
    ContributionAttendanceID: 3,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Add to the Powerpoint Presentation including extended ideas for your chosen section: Our Solution and Target Customers",
    ContributionAttendanceName: "Left early",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 3",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "DARCY, Alexander (K9989999)",
  },
  {
    ContributionID: 16,
    ContributionLogID: 3,
    ContributionUserID: 464,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Add to the Powerpoint Presentation including extended ideas for your chosen section: Competitors ",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 3",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "OBOUSY, Usama (K7463732)",
  },
  {
    ContributionID: 17,
    ContributionLogID: 3,
    ContributionUserID: 325,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 2,
    ContributionFuturetasks:
      "Add to the Powerpoint Presentation including extended ideas for your chosen section: Business Canvas Model and Funding",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Partially completed",
    ContributionLogName: "Week 3",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "BHAMRA, Shakiba (K9804915)",
  },
  {
    ContributionID: 14,
    ContributionLogID: 3,
    ContributionUserID: 474,
    ContributionAttendanceID: 2,
    ContributionCompletionID: 3,
    ContributionFuturetasks:
      "Add to the Powerpoint Presentation including extended ideas for your chosen section: Our Problem and Problem Location",
    ContributionAttendanceName: "Late arriving",
    ContributionCompletionName: "Completed late",
    ContributionLogName: "Week 3",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "PAULINO DA SILVA, Marius (K2831579)",
  },
];
export default log3Contributions;

