const log2Contributions = [
  {
    ContributionID: 8,
    ContributionLogID: 2,
    ContributionUserID: 289,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Restructure our idea on carbon emissions and green energy. (Focus on transport causing pollution.  Which city in England has the worst traffic pollution? Why?)",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 2",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "ALAHMAD, Samir (K7907243)",
  },
  {
    ContributionID: 9,
    ContributionLogID: 2,
    ContributionUserID: 474,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Restructure our idea on carbon emissions and green energy. (App focusing on improving carbon footprint-what will entice customers to do this?) ",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 2",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "PAULINO DA SILVA, Marius (K2831579)",
  },
  {
    ContributionID: 11,
    ContributionLogID: 2,
    ContributionUserID: 464,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Restructure our idea on carbon emissions and green energy. (What makes us unique and what are the rewards for customers altering their lifestyle for carbon footprint advantages?) ",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 2",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "OBOUSY, Usama (K7463732)",
  },
  {
    ContributionID: 12,
    ContributionLogID: 2,
    ContributionUserID: 325,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Restructure our idea on carbon emissions and green energy. (Public benefits and Economic benefits?)",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 2",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "BHAMRA, Shakiba (K9804915)",
  },
  {
    ContributionID: 10,
    ContributionLogID: 2,
    ContributionUserID: 343,
    ContributionAttendanceID: 2,
    ContributionCompletionID: 3,
    ContributionFuturetasks:
      "Restructure our idea on carbon emissions and green energy. (App focusing on improving carbon footprint-who are our customers? How do we appeal to these customers?) ",
    ContributionAttendanceName: "Late arriving",
    ContributionCompletionName: "Completed late",
    ContributionLogName: "Week 2",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "DARCY, Alexander (K9989999)",
  },
];
export default log2Contributions;

