const log5Contributions = [
  {
    ContributionID: 23,
    ContributionLogID: 5,
    ContributionUserID: 289,
    ContributionAttendanceID: 3,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Meet up online and practice the power-point run through",
    ContributionAttendanceName: "Left early",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 5",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "ALAHMAD, Samir (K7907243)",
  },
  {
    ContributionID: 24,
    ContributionLogID: 5,
    ContributionUserID: 474,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Meet up online and practice the power-point run through",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 5",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "PAULINO DA SILVA, Marius (K2831579)",
  },
  {
    ContributionID: 25,
    ContributionLogID: 5,
    ContributionUserID: 343,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Meet up online and practice the power-point run through",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 5",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "DARCY, Alexander (K9989999)",
  },
  {
    ContributionID: 26,
    ContributionLogID: 5,
    ContributionUserID: 464,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Meet up online and practice the power-point run through",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 5",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "OBOUSY, Usama (K7463732)",
  },
  {
    ContributionID: 27,
    ContributionLogID: 5,
    ContributionUserID: 325,
    ContributionAttendanceID: 1,
    ContributionCompletionID: 1,
    ContributionFuturetasks:
      "Meet up online and practice the power-point run through",
    ContributionAttendanceName: "Present throughout",
    ContributionCompletionName: "Completed",
    ContributionLogName: "Week 5",
    ContributionLogGroupID: 1,
    ContributionLogGroupName: "Group A01",
    ContributionLogUserName: "BHAMRA, Shakiba (K9804915)",
  },
];
export default log5Contributions;

