// DO NOT EDIT THIS FILE
// DUPLICATE IT AND NAME IT apiURL.js

// If you're using the softwarehub.uk api : simply duplicate this file
// and name the new one apiURL.js so it can be used by the application.
// If you want to use a local api (such as "http://localhost:5000/api")
// by running the UniBase server locally:
// duplicate this file and modify the API_URL below accordingly.
// This file itself is not used by the application.

// this is done so the apiURL.js can be ignored by git, and team members can use different servers.

const API_URL = "https://softwarehub.uk/unibase/api";

export default API_URL;
